### ISSUE TITLE
can not use @MapperFactory and have dependency on other mapper at the same time

### ISSUE THREAD

**Issue by lesaint** [lesaint/damapping#43]
Currently, `@MapperFactory` annotation is supported only on constructor or static class/enum methods.

So, by design, we can not have a mapper that would use `@MapperFactory` and be at the top of a tree mapping (ie. use at least one generated mapper to map properties).

This issue needs work as don't see any obvious way of implementing this feature yet.

**Comment by lesaint** [comment]
@fbiville suggestion in issue #59 is for any method annotated with `@MapperFactory` to provide specific support for parameters which are a generated type. The idea is interesting but limited by design.

## using parameter annotations

I think we need to use an annotation on the parameters of the method annotated with `@MapperFactory` to identify which parameter must be used as parameters of the `MapperFactory` interfaces methods and which must be used as parameter of the `MapperFactoryImpl` constructor. 

### example

The following example reuses the `@MapperFactory` to annotate the parameters which must be used for the factory method:

```java
@Mapper
public class FooToBla implements Function<Foo,Bla> {

    @MapperFactory
    public FooToBla(@MapperFactory HttpHeaders headers,
                               FooToBazMapper fooToBazMapper,
                               BazToBlaMapper bazToBlaMapper) {
        // [...]
    }
}
```

Generated code:

```java
public class FooToBlaMapperFactoryImpl implements FooToBlaMapperFactory {
    private final FooToBazMapper fooToBazMapper;
    private final BazToBlaMapper bazToBlaMapper;

    public FooToBlaMapperFactoryImpl(FooToBazMapper fooToBazMapper,
                                                              BazToBlaMapper bazToBlaMapper) {
        this.fooToBazMapper = fooToBazMapper;
        this.bazToBlaMapper = bazToBlaMapper;
    }

    @Override
    @Nonnull
    public FooToBlaMapper get(HttpHeaders headers) {
        return new FooToBlaMapperImpl(new FooToBla(headers, fooToBazMapper, bazToBlaMapper));
    }

    private static class FooToBlaMapperImpl implements FooToBlaMapper {
        private final FooToBla instance;

        public FooToBlaMapperImpl(FooToBla instance) {
            this.instance = instance;
        }

        @Override
        @Nullable
        public Bla apply(Foo foo) {
            return instance.apply(foo);
        }
    }
}
```

### parameter annotation documentation

I think we should use the following rules for this new behavior based on parameter annotations:

1. if method is annotated with `@MapperFactory` and has no parameter annotated with `@MapperFactory`, all parameters are used as parameters of the `MapperFactory` interface methods
    * this rule provide backward compatibility with current implementation
2. if at least one parameter of a method annotated with `@MapperFactory` is annotated with `@MapperFactory` then only the parameters explicitly annotated with `@MapperFactory` will be used as parameters of the `MapperFactory` interface methods
    * all other parameters will be used as parameters of the constructor of the `MapperFactoryImpl` class, ie. they are dependencies of the `MapperFactoryImpl` class

### compatibility with `@Injectable`

This approach is naturally compatible with `@Injectable` and will integrate well with any dependency injection framework.

### discussion on reusing the `@MapperFactory` annotation

This design proposal is based on the reuse the `@MapperFactory` annotation. This implies that the annotated parameters will be those of the `MapperFactory` interface method.

We could choose to annotate the parameters that will be used as the parameters of the constructor of the `MapperFactoryImpl` class. The `@MapperFactory` could not be reused because it would be hard to define a backward compatible rule for the current implementation without twisting the semantic of the annotation's name. We would therefor need a new annotation.

Beside the fact that I don't know how to name this new annotation, my gut feeling is that the first approach will usually require annotating less parameters. I make sense to believe that a Mapper can have many dependencies but only few factory parameters, does it not ?

**Comment by fbiville** [comment]
:+1:

**Comment by lesaint** [comment]
working on the IDEA plugin right now, hopefull will release a beta this week for IDEA 14 and DAMapping framework 0.6.0. This issue is my next subject.

**Comment by lesaint** [comment]
Thinking a little bit more about this new feature, the following points came up:

### factory method without parameter?

The current suggested implementation does not support the case a method annotated with `@MapperFactory` which would have only dependencies (which will generate a method in MapperFactory interface which has no parameters).

This is the counter example that advocates to annotate the dependency parameters instead of annotating the factory method parameters.

Which means we **need a new annotation and we need to name it**.

This goes the opposite way of the discussion in the previous comment but, assuming we find a name for the new annotation, I think that in the end I more comfortable with the fact the `@MapperFactory` annotation stays a method/constructor annotation, especially in the light of the following issues.

### multiple annotated methods on the dedicated class

What about dedicated class with more than one constructor annotated with `@MapperFactory`?

Since one method having at least one parameter annotated with `@MapperFactory` means altering the constructor of the generated MapperFactoryImpl class, having another method annotated with `@MapperFactory` will also have an effect on the same constructor => problem.

I see the following options:

* option1: not supporting more than one method annotated with `@MapperFactory` that defines dependencies, raise a compilation error in such case
    - most simple implementation
* option 2: if at least one method annotated with `@MapperFactory` defines at least one dependency, all methods annotated with `@MapperFactory` must define the same dependencies
    - "same" is defined as same type and same name, order does not matter
* option 3: merge dependencies defined by all methods so that constructor takes all parameters from all the methods annotated with `@MapperFactory`
    - merge  will use the "same" definition of option 2
    - I think this option is bad. My feeling is that it defies the point of the developer defining methods with different dependencies. That why I would prefer option 4 or 5 to it.
* option 4: generate one constructor for each unique set of dependencies
    - set of dependencies will be identified using the "same" definition of option 2 and ignoring order
    - though it is technically possible to implement this option, I don't like the fact that there will be more than one way to create the MapperFactoryImpl class. It is especially troubling when thinking of CDI frameworks integration.
* option 5: generate one MapperFactoryImpl class for each unique set of dependencies
    - set of dependencies will be identified using the "same" definition of option 2 and ignoring order
    - generating multiple MapperFactoryImpl requires using different names. We can either get the name from the methods (but which one if multiple methods have the same set of dependencies?) or require a name be specified by the user (eg. has a parameter of the `@MapperFactory` annotation of the method?)

There may be other options but from those we already have listed, things get quickly complex.
Since I don't know yet if having more than one `@MapperFactory` method is of any use. I think I will implement option 1 for now and maybe option 2 in a second time.

Inputs on the subject are welcome.

### static methods

Shall/can we support this new feature on static methods annotated with `@MapperFactory`?

* option 1: no support, raise a compilation error when `@MapperFactory` is used on a parameter of a static method
    - we end up with a different behavior depending on whether a constructor or a static method is annotated with `@MapperFactory`
* option 2: supporting for static methods the same way we support it for constructors
    - since I am not ever sure static methods annotated with `@MapperFactory` are useful today, is it worth the effort?
* option 3: remove support for static methods annotated with `@MapperFactory` completely
    - well, since we don't even know annotated static methods are even useful, it may be a nice option
    - note that we loose support for the [factory of singletons pattern](http://www.javatronic.fr/damapping/framework/documentation/#factory-of-singletons) in the process

I am tempted to go the conservative way here and implement option 1 first and then decide between option 2 and 3 later.

**Comment by fbiville** [comment]
Intuitively, I'd go for the combo option 4/option 2.

**Comment by lesaint** [comment]
The current solution goes option 2 (with compile error) - option 2.

**Comment by lesaint** [comment]
done
