### ISSUE TITLE
Support Guava's Function defined on any super type (class or interface) of the dedicated class

### ISSUE THREAD

**Issue by fbiville** [lesaint/damapping#60]
Here is my problem: 

```java
public abstract class A<T> implements Function<T, Bar> {
    public A(HttpHeaders headers, ...) {}
    public final Bar apply(T t) {
        return doSomething();
    }

   public abstract Bar doSomething();
}

@Mapper
public class B extends A<Foo> {

    @MapperFactory
    public B(HttpHeaders headers, ...) {
        super(headers, ...);
    }

    public Bar doSomething() {
        // ...
    }
}
```

This triggers a compilation error although it shouldn't:
```
[ERROR] Mapper must have one and only one method qualifying as mapper method (either implemente Guava's Function interface or define a single non private method)
```

In short inherited Function apply should be detected.

**Comment by fbiville** [comment]
Note that adding the following method to `B`:

```java
public Bar apply(Foo foo) {
    return super.apply(foo);
}
```

will only delay the problem.
The generated Mapper interface won't extend any types, as the Function type implemented in `A` is not detected.

**Comment by fbiville** [comment]
A start would be (cf. `JavaxParsingServiceImpl`):

```java
  private Collection<? extends Element> allMethods(TypeElement classElement) {
    Collection<Element> result = new ArrayList<>();
    result.addAll(classElement.getEnclosedElements());


    TypeMirror superclass = classElement.getSuperclass();
    TypeElement element = (TypeElement) processingEnv.getTypeUtils().asElement(superclass);
    if (element.getQualifiedName().toString().startsWith("java.lang")) {
      return result;
    }

    result.addAll(allMethods(element));
    return result;
  }
```

Remaining problems:

 - generated interface does not extend Function
 - apply generic parameter is not resolved (and then does not compile)

**Comment by lesaint** [comment]
Hello, 

Thanks for reporting the issue.

The DAMapping framework does indeed not support class hierarchy of mappers. I didn't think that would actually be of any use. I couldn't figure what kind of behavior could actually be held by an abstract class since mappers are supposed to hold quite atomic pieces of code.

While I work out support for it, here is something that I think should workaround the problem (not tested):

```java
@Mapper
public class B extends A<Foo> implements Function<Foo, Bar> {

    @MapperFactory
    public B(HttpHeaders headers, ...) {
        super(headers, ...);
    }

    public Bar doSomething() {
        // ...
    }
}
```

**Comment by fbiville** [comment]
In my usecase, I define many mappers doing a similar work: converting an entity to a JAX-RS response. While the mapping itself is different from entity to entity, the rest can be abstracted away (therefore the abstract class).

This is feasible, although generic parameter resolution is going to be tricky.

**Comment by lesaint** [comment]
@fbiville, does the workaround actually work for you?

I agree, this feature can be implemented.

**Comment by fbiville** [comment]
This workaround works, except I'm blocked by https://github.com/lesaint/damapping/issues/59

**Comment by lesaint** [comment]
did you take a look at #43 ? I would welcome some user feedback on the solution I suggest

**Comment by lesaint** [comment]
Nailed that one, generics included! 

Fix available in branch `support_dedicated_class_hierarchy`

**Comment by fbiville** [comment]
Will try to test it tomorrow.

**Comment by lesaint** [comment]
done
